### PR TITLE
V2.5.5

### PR DESCRIPTION
**Pull request by zachariapopcorn**
**MAJOR HOTFIX RELEASE**
This fixes two bugs, one minor, one major. It is recommend to update ASAP

The minor bug was in the setup script that forgot to save the config's database value, resetting it on update

The major bug was in the database required commands as it would fail to do anything if the datastore didn't exist (which for first time users, would be true)

### CODE REVIEW

**Comment by SD-SapphireDevelopment** [comment]
Does the setupscript update all the scripts in-game without having to
replace them? Because I'm still getting this error:

User Data

Username: BianaryHood
Roblox ID: 44997379

Group Data

Rank Name: [⭐️] Overseer
Rank ID: 254
Is User Group Banned: No
Is User Suspended: No

Game Data -- It still says "Unable to load"..

Is User Banned: Unable to Load
Is User Muted: Unable to Load
Warnings: Unable to Load

**Comment by zachariapopcorn** [comment]
It works for me just fine. Did you update?

**Comment by zachariapopcorn** [comment]
Kicking works for me

**Comment by SD-SapphireDevelopment** [comment]
It might be because I changed the kick to instead teleport the person
If I send the roblox main script code can you take a look for me?

**Comment by zachariapopcorn** [comment]
Teleporting can fail so that's probably what's happening

**Pull request merged**
